apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depy
  namespace: default
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: tickets
  replicas: 1
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: huxdev/tixer-tickets
          env:
            - name: MONGODB_URI
              value: mongodb://tickets-mongo-svc:27017/tickets
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
